version: '2'
services:
 
  postgres:
    restart: always
    image: "postgres"
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
     POSTGRES_DB: freshdesk-dev-
    ports: 
      - "5432:5432"
  web:
    build: .
    ports:
     - "5000:5000"
     - "8000:8000"
    volumes:
     - .:/usr/src/freshdesk
    links:
      - postgres
