version: '2'
services:

  db:
    restart: always
    image: "postgres"
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
     POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  web:
    build: .
    ports:
     - "5000:5000"
     - "8000:8000"
    links:
      - db
